const MenuActionTypes = {
  GET_CURRENT_ITEM: "GET_CURRENT_ITEM",
  FETCH_MENU_START: "FETCH_MENU_START",
  FETCH_MENU_SUCCESS: "FETCH_MENU_SUCCESS",
  FETCH_MENU_FAILURE: "FETCH_MENU_FAILURE",
};

export default MenuActionTypes;
